version: "3.7"
services:
  app:
    build: ./app
    links:
      - mysql_db
    ports:
      - "5000:5000"
    volumes:
      - .:/app
  mysql_db:
    image: mysql:latest
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - mysql_data:/var/lib/mysql

  redis:
    image: "redis:alpine"

volumes:
  mysql_data:
